version: '3.8'

services:
  #database section
  testdb:
    image: redis/redis-stack:latest

  #microservices api section
  test.api:
    image: ${DOCKER_REGISTRY-}test-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./TestRedis
      dockerfile: Dockerfile

    
#network section
networks:
  default:
    name: test_microservices
    driver: bridge
